# Generated by Django 5.1.4 on 2025-01-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("lecturer", models.CharField(max_length=250)),
                ("group", models.CharField(max_length=250)),
                ("time", models.TimeField()),
                ("classroom", models.CharField(max_length=250)),
                ("date", models.DateTimeField()),
                ("file", models.FileField(blank=True, upload_to="lessons/")),
                ("slug", models.SlugField(max_length=1000, unique=True)),
                (
                    "categories",
                    models.ManyToManyField(
                        related_name="categories", to="main.category"
                    ),
                ),
            ],
        ),
    ]
