# Generated by Django 5.1.4 on 2025-01-04 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="categories",
        ),
        migrations.AlterField(
            model_name="lesson",
            name="date",
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name="lesson",
            name="categories",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="main.category",
            ),
        ),
    ]
