# Generated by Django 5.1.4 on 2025-01-04 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_rename_time_lesson_start_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lesson",
            old_name="categories",
            new_name="category",
        ),
    ]
