# Generated by Django 5.1.4 on 2025-01-25 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_rename_categories_lesson_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="stud_on_lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name="lesson",
            name="verification_code",
            field=models.IntegerField(default=0),
        ),
    ]
