# Generated by Django 5.1.4 on 2025-01-25 02:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_stud_on_lesson_lesson_verification_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="verified_user",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
