# Generated by Django 5.1.4 on 2025-01-25 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_alter_lesson_verified_users"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="verified_users",
        ),
    ]
