# Generated by Django 5.1.4 on 2025-01-25 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_remove_lesson_verified_users"),
        ("users", "0002_remove_profile_name_alter_profile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="verified_lessons",
            field=models.ManyToManyField(to="main.lesson"),
        ),
    ]
